change entrypoint
Signed-off-by: Oguz Ozturk <oguzkaganozt@gmail.com>

diff --git a/docker/etc/simulation/config/change_parameters b/docker/etc/simulation/config/change_parameters
--- a/docker/etc/simulation/config/change_parameters
+++ b/docker/etc/simulation/config/change_parameters
@@ -1,8 +1,5 @@
 #!/bin/bash
 
-result_file=/autoware/result.txt
-sed -i "s|output_file:.*|output_file: ${result_file}|" /opt/autoware/share/autoware_planning_evaluator/config/planning_evaluator.param.yaml
-
 # Define simulation parameters in a table according to the simulation id
 declare -A params=(
     [1]="9.0 1.5"   # ego cant complete the scenario
@@ -19,12 +16,17 @@ else
     HARD_MARGIN=0.2
 fi
 
-# change common parameters
-src_path=/autoware/config/common.param.yaml
-dest_path=/opt/autoware/share/autoware_launch/config/planning/scenario_planning/common
-sed -i "3s/max_vel:.*/max_vel: ${MAX_VEL}/" "$src_path"
+# change planning evaluator output file
+if sed -i "s|output_file:.*|output_file: ${OUTPUT_FILE}|" /opt/autoware/share/autoware_planning_evaluator/config/planning_evaluator.param.yaml; then
+    echo -e "\e[32mPlanning evaluator output file is set to ${OUTPUT_FILE}\e[0m"
+else
+    echo -e "\e[31mError: Failed to set planning evaluator output file\e[0m" >&2
+    exit 1
+fi
 
-if cp "$src_path" "$dest_path"; then
+# change common parameters
+common_param_path=/opt/autoware/share/autoware_launch/config/planning/scenario_planning/common/common.param.yaml
+if sed -i "3s/max_vel:.*/max_vel: ${MAX_VEL}/" "$common_param_path"; then
     echo -e "\e[32mCommon parameters successfully changed\e[0m"
 else
     echo -e "\e[31mError: Failed to change common parameters\e[0m" >&2
@@ -32,11 +34,8 @@ else
 fi
 
 # change static obstacle avoidance parameters
-src_path=/autoware/config/static_obstacle_avoidance.param.yaml
-dest_path=/opt/autoware/share/autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module
-sed -i "71s/hard_margin:.*/hard_margin: ${HARD_MARGIN}/" "$src_path"
-
-if cp "$src_path" "$dest_path"; then
+static_obstacle_avoidance_param_path=/opt/autoware/share/autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/static_obstacle_avoidance.param.yaml
+if sed -i "71s/hard_margin:.*/hard_margin: ${HARD_MARGIN}/" "$static_obstacle_avoidance_param_path"; then
     echo -e "\e[32mStatic obstacle avoidance parameters successfully changed\e[0m"
 else
     echo -e "\e[31mError: Failed to change static obstacle avoidance parameters\e[0m" >&2
