add simulator output
Signed-off-by: Oguz Ozturk <oguzkaganozt@gmail.com>

diff --git a/docker/etc/simulation/config/change_parameters b/docker/etc/simulation/config/change_parameters
--- a/docker/etc/simulation/config/change_parameters
+++ b/docker/etc/simulation/config/change_parameters
@@ -1,6 +1,9 @@
 #!/bin/bash
 
 # Define simulation parameters in a table according to the simulation id
+# [SIMULATION_ID] [MAX_VEL] [HARD_MARGIN]
+# MAX_VEL is in m/s is the maximum velocity of the ego vehicle
+# HARD_MARGIN is in m is the hard margin for the static obstacle avoidance
 declare -A params=(
     [1]="9.0 1.5"   # ego cant complete the scenario
     [2]="9.0 1.0"   # ego cant complete the scenario
@@ -12,13 +15,15 @@ if [[ -v params[$SIMULATION_ID] ]]; then
     read -r MAX_VEL HARD_MARGIN <<< "${params[$SIMULATION_ID]}"
 else
     # Default values if SIMULATION_ID is not in the table
+    echo -e "\e[31mError: SIMULATION_ID is not in the table\e[0m" >&2
+    echo -e "\e[31mUsing default values\e[0m" >&2
     MAX_VEL=4.17
     HARD_MARGIN=0.2
 fi
 
 # change planning evaluator output file
-if sed -i "s|output_file:.*|output_file: ${OUTPUT_FILE}|" /opt/autoware/share/autoware_planning_evaluator/config/planning_evaluator.param.yaml; then
-    echo -e "\e[32mPlanning evaluator output file is set to ${OUTPUT_FILE}\e[0m"
+if sed -i "s|output_file:.*|output_file: ${PLANNING_OUTPUT_FILE}|" /opt/autoware/share/autoware_planning_evaluator/config/planning_evaluator.param.yaml; then
+    echo -e "\e[32mPlanning evaluator output file is set to ${PLANNING_OUTPUT_FILE}\e[0m"
 else
     echo -e "\e[31mError: Failed to set planning evaluator output file\e[0m" >&2
     exit 1
